<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>SaviouR</title>

<script src="saviouR_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="saviouR_files/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="saviouR_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="saviouR_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="saviouR_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="saviouR_files/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="saviouR_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="saviouR_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="saviouR_files/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">SaviouR</h1>
<h3 class="subtitle"><em>How to talk to a computer</em></h3>

</div>


<p>We appreciate that the first contact with <code>R</code> might feel a little overwhelming, especially if you haven’t done any programming before. Some things are fairly easy to understand but others do not come naturally to people. To help you with the latter group, here are some tips on how to approach talking to computers.</p>
<div id="horses-for-courses" class="section level1">
<h1>Horses for courses</h1>
<p>We keep telling you to try and use the script editor window for writing and running code instead of the console. There is a good reason for this. If you write a command and it doesn’t do exactly what you wanted to do, you can quickly tweak it in the editor and run it again. Also, if you accidentally modify and object and mess everything up, you can just re-run your entire script up to that point and pretend nothing ever happened. Or different still, let’s say you analysed your data and wrote your report and then you realised you made a mistake, for instance forgot to exclude data you should have excluded or excluded some you shouldn’t have. Without a “paper-trail” of your analysis, this is a very unpleasant (but, sadly, not unheard of) experience. But with a saved analysis script, you can just insert an additional piece of code in the file, re-run it and laugh it off. Or do the first two, and then take a long hard look at yourself! Whatever the case, using the script editor is just very, very useful!</p>
<p>However, the aim is to keep the script tidy. You don’t need to put <em>every</em> single line of code you ever run into it. Sometimes, you just want to look at your data, using, for example <code>View(df)</code>. This kind of command really doesn’t need to be in your script. As a general rule of thumb, <strong>use the editor for code that adds something of value to the sequence of the script</strong> (data cleaning, analysis, code generating plots, tables, <em>etc.</em>) <strong>and the console for one-off commands</strong> (when you want to just check something).</p>
<p>Here is an example of what a <a href="https://osf.io/256xy/" target="_blank">neat script</a> looks like (part of the <em>Reproducibility Project: Psychology</em> analysis<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a>). Compare it to your own scripts and try to find ways of improving your coding.</p>
<p>For useful “good practice” guidance on how to write legible code, see the <a href="https://google.github.io/styleguide/Rguide.xml" target="_blank">Google style guide</a>.</p>
</div>
<div id="coopr" class="section level1">
<h1>CoopR</h1>
<p>Talking to a computer is like talking to Sheldon Cooper (of <em>The Big Bang Theory</em> fame): he is a highly proficient user of the English language: he understands the vocab, grammar, and syntax perfectly well. Since he is very smart, he can do many complex things you ask him to do, <em>so long as you are formal, logical, precise, and unambiguous</em>. If you are not, he won’t be able to help you or worse, will do something wrong. When it comes to the pragmatics of English, he’s a bit lost: he doesn’t understand metaphors, shorthand, or sarcasm. If you want to tell jokes, you’d be better off talking to someone else.</p>
<p>Keep this analogy in mind whenever you’re working with <code>R</code>. Talk to it as you would talk to Sheldon: don’t take anything for granted, don’t rely on <code>R</code> to make any assumptions about what you are telling it. Certainly don’t try to be funny and expect <code>R</code> to appreciate it! It takes a little practice to get into the habit of translating what you want to do into the dry, formal language of logic and algorithms but, on the flip side, once you get the knack of it, there will never be any misunderstanding on the part of the machine. With people, there will always be miscommunication, no matter how clear you try to be, because people are very sensitive to paralinguistic cues, non-verbal communication, and the pragmatics of a language. Computers don’t care about any of that and thus, if they’re not doing what you want them to, the problem is in the sender, not the receiver.<a href="#fn2" class="footnoteRef" id="fnref2"><sup>2</sup></a> That is exactly why they’re built like that!</p>
<p>Instead of thinking about computers as scary, abstruse, or boring, learn to appreciate this quality of precision as beautiful. That way, you’ll get much more enjoyment out of working with them.</p>
</div>
<div id="key-principles-of-r-programming" class="section level1">
<h1>Key principles of <code>R</code> programming</h1>
<p>The previous section wasn’t meant to be an empty lead in for what’s coming next. Think back to the <code>CoopR</code> analogy when you read about the following core principles of working with <code>R</code>.</p>
<div id="think-algorithmically" class="section level2">
<h2>Think algorithmically</h2>
<p>By algorithmically, we mean in a precise <em>step-by-step</em> fashion where each action is equivalent to the smallest possible increment. So, if you want a machine to make you a cup of tea, instead of saying: “Oi <code>CoopR</code>! Fetch me a cuppa!”, you need to break everything down. Something like this:</p>
<ol>
<li><code>Go to kitchen</code></li>
<li><code>If no kitchen, jump to 53</code></li>
<li><code>Else get kettle</code></li>
<li><code>If no kettle, jump to 53</code></li>
<li><code>Check how much water in kettle</code></li>
<li><code>If is more or equal than 500 ml of water in kettle, jump to 15</code></li>
<li><code>Place kettle under cold tap</code></li>
<li><code>Open kettle lid</code></li>
<li><code>Turn cold tap on</code></li>
<li><code>Check how much water in kettle</code></li>
<li><code>If there is more than 500 ml of water in kettle, jump to 13</code></li>
<li><code>Jump to 10</code></li>
<li><code>Turn cold tap off</code></li>
<li><code>Close kettle lid</code></li>
<li><code>If kettle is on base, jump to 17</code></li>
<li><code>Place kettle on base</code></li>
<li><code>If base is plugged in mains, jump to 19</code></li>
<li><code>Plug base in mains</code></li>
<li><code>Turn kettle on</code></li>
<li><code>Get cup</code></li>
<li><code>If no cup, jump to 53</code></li>
<li><code>Get tea bag</code> # <em>yeah, we’re not posh</em></li>
<li><code>If no tea bag, jump to 53</code></li>
<li><code>Put tea bag in cup</code></li>
<li><code>If kettle has boiled, jump to 27</code></li>
<li><code>Jump to 25</code></li>
<li><code>Start pouring water from kettle to cup</code></li>
<li><code>Check how much water in cup</code></li>
<li><code>If there is more than 225 ml of water in cup, jump to 31</code></li>
<li><code>Jump to 28</code></li>
<li><code>Stop pouring water from kettle</code></li>
<li><code>Return kettle on base</code></li>
<li><code>Wait 4 minutes</code></li>
<li><code>Remove tea bag from cup</code></li>
<li><code>Place tea bag by edge of sink</code> # <em>this is obviously your flatmate’s program</em></li>
<li><code>Open fridge</code></li>
<li><code>Search fridge</code></li>
<li><code>If full fat milk is not in fridge, jump to 41</code></li>
<li><code>Get full fat milk</code> # <em>full fat should be any sensible person’s top choice. True fact!</em></li>
<li><code>Jump to 43</code></li>
<li><code>If semi-skimmed milk is not in fridge, jump to 51</code> # <em>skimmed is not even an option!</em></li>
<li><code>Get semi-skimmed milk</code></li>
<li><code>Take lid of milk</code></li>
<li><code>Start pouring milk in cup</code></li>
<li><code>Check how much liquid in cup</code></li>
<li><code>If more or equal to 250 ml liquid in cup, jump to 48</code></li>
<li><code>Jump to 45</code></li>
<li><code>Stop pouring milk</code></li>
<li><code>Put lid on milk</code></li>
<li><code>Return milk to fridge</code></li>
<li><code>Close fridge</code> # <em>yes, we kept it open! Fewer steps (I’m not lazy, I’m optimised!)</em></li>
<li><code>Bring cup</code> # <em>no need to stir</em></li>
<li><code>Finish</code></li>
</ol>
<p>… so there you go, a nice cuppa in 53 easy steps!</p>
<p>Obviously, this is not real code but something called <em>pseudocode</em>: a program-like set of instructions expressed in a more-or-less natural language. Surely, we could get even more detailed, <em>e.g.,</em> by specifying what kind of tea we want, but 53 steps is plenty. Notice, however, that, just like in actual code, the entire process is expressed in a sequential manner. This sometimes means that you need to think about how to say things that would be very easy to communicate to a person (<em>e.g.,</em> “Wait till the kettle boils”) in terms of well-defined repeatable steps. In our example, this is done with a loop:</p>
<blockquote>
<ol start="25" style="list-style-type: decimal">
<li><code>If kettle has boiled, jump to 27</code></li>
<li><code>Jump to 25</code></li>
<li><code>Start pouring water from kettle to cup</code></li>
</ol>
</blockquote>
<p>The program will check if the kettle has boiled and, if it has, it will start pouring water into the cup. If it hasn’t boiled, it will jump back to 25. and check again if it has boiled. This is equivalent to saying “wait till the kettle boils”.</p>
<p>Note that in actual <code>R</code> code, certain expressions, such as <code>jump to</code> (or, more frequently in some older programming languages <code>goto</code>) are not used so you would have to find other ways around the problem, were you to write a tea-making program in <code>R</code>. However, this example illustrates the sort of thinking mode you need to get into when talking to computers.</p>
<p>To demonstrate this point on an actual programming example that will be familiar to you, let’s think about how to conceptually ask <code>R</code> to replace every value in column 1 of matrix <code>mat</code> that is more than 2 standard deviations above the mean with <code>NA</code>s. In a step-by-step fashion, we would ask:</p>
<ol>
<li><code>Calculate mean of column 1 of mat and store in m_mat1</code></li>
<li><code>Calculate standard deviation of column 1 of mat and store in sd_mat1</code></li>
<li><code>Calculate m_mat1 plus twice sd_mat1 and store in value</code></li>
<li><code>Compare each number in column 1 of mat against value and return TRUE if that element is larger than value and FALSE otherwise. Store this chain of TRUEs and FALSEs into condition</code></li>
<li><code>Take all elements of column 1 of mat that correspond to TRUEs in condition and assign NA to them</code></li>
</ol>
<p>In actual <code>R</code> code, this algorithm corresponds to:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># step 1</span>
m_mat1 &lt;-<span class="st"> </span><span class="kw">mean</span>(mat[ , <span class="dv">1</span>]) <span class="co"># the indexing is saying [-all rows-, column 1]</span>

<span class="co"># step 2</span>
sd_mat1 &lt;-<span class="st"> </span><span class="kw">sd</span>(mat[ , <span class="dv">1</span>])

<span class="co"># step 3</span>
value &lt;-<span class="st"> </span>m_mat1 <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>sd_mat1

<span class="co"># step 4</span>
condition &lt;-<span class="st"> </span>mat[ , <span class="dv">1</span>] <span class="op">&gt;</span><span class="st"> </span>value

<span class="co"># step 5</span>
mat[condition, <span class="dv">1</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></code></pre></div>
<p> </p>
<p>And yes, you can ram all of the above into a single line of code, such as</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat[mat[ , <span class="dv">1</span>] <span class="op">&gt;</span><span class="st"> </span><span class="kw">mean</span>(mat[ , <span class="dv">1</span>]) <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">sd</span>(mat[ , <span class="dv">1</span>]), <span class="dv">1</span>]</code></pre></div>
<p>but before you get to the stage where that becomes second nature and you are confident that you won’t miss out any <code>[]</code>s, <code>()</code>s, <code>,</code>s, or <code>1</code>s, it might be a good idea to do things in sequence. That way, you will teach yourself to think algorithmically about programming tasks.</p>
<p> </p>
</div>
<div id="if-you-want-to-keep-it-put-it-in-a-box" class="section level2">
<h2>If you want to keep it, put it in a box</h2>
<p>Everything in life is merely transient; we ourselves are pretty ephemeral beings. (#sodeepbro) However, <code>R</code> takes this quality and runs with it. If you ask <code>R</code> to perform any operation, it will spew it out into the console and immediately forget it ever happened. Let’s show you what that means:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create an object a and assign it the value of 1</span>
a &lt;-<span class="st"> </span><span class="dv">1</span>

<span class="co"># increment a by 1</span>
a <span class="op">+</span><span class="st"> </span><span class="dv">1</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># OK, now see what the value of a is</span>
a</code></pre></div>
<pre><code>## [1] 1</code></pre>
<p> </p>
<p>So, <code>R</code> as if forgot we asked it to do <code>a + 1</code> and didn’t change its value. The only way to keep this new value is to <em>put it in an object</em>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">b &lt;-<span class="st"> </span>a <span class="op">+</span><span class="st"> </span><span class="dv">1</span>

<span class="co"># now let&#39;s see</span>
b</code></pre></div>
<pre><code>## [1] 2</code></pre>
<p> </p>
<p>Think of objects as boxes. The names of the objects are only <em>labels</em>. Just like with boxes, it is convenient to label boxes in a way that is indicative of their contents, but the label itself does not determine the content. Sure, you can create an <code>R</code> object called <code>one</code> and store the value of <code>2</code> in it, if you wish. But you might want to think about whether or not it is a helpful name. And what kind of person that makes you… Objects can contain anything at all: values, vectors, matrices, data, graphs, tables, even code. In fact, every time you call a function, <em>e.g.,</em> <code>mean()</code>, you are running the code that’s inside the object <code>mean</code> with whatever values you pass to the arguments of the function.</p>
<p>Let’s demonstrate this last point:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># let&#39;s create a vector of numbers the mean of which I want to calculate</span>
vec &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">103</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">3</span>, <span class="dv">43</span>, <span class="dv">2</span>, <span class="dv">23</span>, <span class="dv">7</span>, <span class="dv">1</span>)

<span class="co"># see what&#39;s inside</span>
vec</code></pre></div>
<pre><code>##  [1] 103   1   1   6   3  43   2  23   7   1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># let&#39;s get the mean</span>
<span class="co"># mean is the sum of all values divided by the number of values</span>
<span class="kw">sum</span>(vec)<span class="op">/</span><span class="kw">length</span>(vec)</code></pre></div>
<pre><code>## [1] 19</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># good, now let&#39;s create a function that calculates</span>
<span class="co"># the mean of whatever we ask it to</span>
<span class="cf">function</span>(x) {<span class="kw">sum</span>(x)<span class="op">/</span><span class="kw">length</span>(x)}</code></pre></div>
<pre><code>## function(x) {sum(x)/length(x)}</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># but as we discussed above, R immediately forgot about the function</span>
<span class="co"># so we need to store it in a box (object) to keep it for later!</span>
calc.mean &lt;-<span class="st"> </span><span class="cf">function</span>(x) {<span class="kw">sum</span>(x)<span class="op">/</span><span class="kw">length</span>(x)}

<span class="co"># OK, all ready now</span>
<span class="kw">calc.mean</span>(<span class="dt">x =</span> vec)</code></pre></div>
<pre><code>## [1] 19</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># the code inside the object calc.mean is reusable</span>
<span class="kw">calc.mean</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">53</span>, <span class="dv">111</span>))</code></pre></div>
<pre><code>## [1] 43</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># to show that calc.mean is just an object with some code in it,</span>
<span class="co"># you can look inside, just like with any other object</span>
calc.mean</code></pre></div>
<pre><code>## function(x) {sum(x)/length(x)}
## &lt;bytecode: 0x0000000009a057d8&gt;</code></pre>
<p> </p>
<p>Let this be your mantra: <strong>“If I want to keep it for later, I need to put it in an object so that is doesn’t go off.”</strong></p>
<p> </p>
</div>
<div id="you-cant-really-change-an-object" class="section level2">
<h2>You can’t <em>really</em> change an object</h2>
<p>Unlike in the physical world, objects in <code>R</code> cannot truly change. The reason is that, sticking to our analogy, these objects are kind of like boxes. You can put stuff in, take stuff out and that’s pretty much it. However, unlike boxes, when you take stuff out of objects, you only take out a copy of its contents. The original contents of the box remain intact. Of course you can do whatever you want (within limits) to the stuff once you’ve taken it out of the box but you are only modifying the copy. And unless you put that modified stuff into a box, <code>R</code> will forget about it as soon as it’s done with it. Now, as you probably know, you can call the boxes whatever you want (again, within certain limits). What might not have occurred to you though, is that you can call the new box the same as the old one. When that happens, <code>R</code> basically takes the label off the old box, pastes it on the new one and burns the old box. So even though some operations in <code>R</code> may look like they change objects, under the hood <code>R</code> copies their content, modifies it, stores the result in a different object puts the same label on it and discards the original object. Understanding this mechanism will make things much easier!</p>
<p>Putting the above into practice, this is how you “change” an <code>R</code> object:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># put 1 into an object (box) called a</span>
a &lt;-<span class="st"> </span><span class="dv">1</span>

<span class="co"># copy the content of a, add 1 to it and store it in an object b</span>
b &lt;-<span class="st"> </span>a <span class="op">+</span><span class="st"> </span><span class="dv">1</span>

<span class="co"># copy what&#39;s inside b and put it in a new object called a</span>
<span class="co"># discarding the old object a</span>
a &lt;-<span class="st"> </span>b

<span class="co"># now see what&#39;s inside of a</span>
<span class="co"># (by copying its content and pasting it in the console)</span>
a</code></pre></div>
<pre><code>## [1] 2</code></pre>
<p> </p>
<p>Of course, you can just cut out the middleman (object <code>b</code>). So to increment <code>a</code> by another <code>1</code>, we can do:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">a &lt;-<span class="st"> </span>a <span class="op">+</span><span class="st"> </span><span class="dv">1</span>

a</code></pre></div>
<pre><code>## [1] 3</code></pre>
<p> </p>
</div>
<div id="its-elementary-my-dear-watson" class="section level2">
<h2>It’s elementary, my dear Watson</h2>
<p>When it comes to data, every vector, matrix, list, data frame - in other words, every structure - is composed of elements. An element is a single number, boolean (<code>TRUE</code>/<code>FALSE</code>), or a character string (anything in “quotes”). Elements come in several <em>classes</em>:</p>
<ul>
<li><p><code>&quot;numeric&quot;</code>, as the name suggests, a numeric element is a <em>single number</em>: 1, 2, -725, 3.14159265, <em>etc.</em>. A numeric element is never in ‘single’ or “double” quotes! Numbers are cool because you can do a lot of maths (and stats!) with them.</p>
<p> </p></li>
<li><p><code>&quot;character&quot;</code>, a string of characters, no matter how long. It can be a single letter, <code>'g'</code>, but it can equally well be a sentence, <code>&quot;Elen síla lumenn' omentielvo.&quot;</code> (if you want the string to contain any single quotes, use double quotes to surround the string with and <em>vice versa</em>). Notice that character strings in <code>R</code> are <em>always</em> in ‘single’ or “double” quotes. Conversely <em>anything in quotes</em> is a character string:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(<span class="dv">3</span>)</code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(<span class="st">&quot;3&quot;</span>) <span class="co"># in quotes, therefore character!</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>It stands to reason that you can’t do any maths with cahracter strings, <strong>not even if it’s a number that’s inside the quotes</strong>!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="st">&quot;3&quot;</span> <span class="op">+</span><span class="st"> &quot;2&quot;</span></code></pre></div>
<pre><code>## Error in &quot;3&quot; + &quot;2&quot;: non-numeric argument to binary operator</code></pre>
<p> </p></li>
<li><p><code>&quot;logical&quot;</code>, a logical element can take one of two values, <code>TRUE</code> or <code>FALSE</code>. Logicals are usually the output of logical operations (anything that can be phrased as a yes/no question, <em>e.g., is x equal to y?</em>). In formal logic, <code>TRUE</code> is represented as 1 and <code>FALSE</code> as 0. This is also the case in <code>R</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># recall that c() is used to bind elements into a vector</span>
<span class="co"># (that&#39;s just a fancy term for an ordered group of elements)</span>
<span class="kw">class</span>(<span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">FALSE</span>))</code></pre></div>
<pre><code>## [1] &quot;logical&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># we can force (&#39;coerce&#39;, in R jargon) the vector to be numeric</span>
<span class="kw">as.numeric</span>(<span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">FALSE</span>))</code></pre></div>
<pre><code>## [1] 1 0</code></pre>
<p>This has interesting implications. First, is you have a logical vector of many <code>TRUE</code>s and <code>FALSE</code>s, you can quickly count the number of <code>TRUE</code>s by just taking the sum of the vector:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># consider vector of 50 logicals</span>
x</code></pre></div>
<pre><code>##  [1]  TRUE FALSE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE FALSE
## [12]  TRUE  TRUE FALSE  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE FALSE
## [23]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE  TRUE  TRUE
## [34]  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE
## [45] FALSE  TRUE FALSE FALSE  TRUE  TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># number of TRUEs</span>
<span class="kw">sum</span>(x)</code></pre></div>
<pre><code>## [1] 30</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># number of FALSEs is 50 minus number of TRUEs</span>
<span class="kw">length</span>(x) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(x)</code></pre></div>
<pre><code>## [1] 20</code></pre>
<p>Second, you can perform all sorts of arithmetic operations on logicals:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># TRUE/FALSE can be shortened to T/F</span>
T <span class="op">+</span><span class="st"> </span>T</code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">F <span class="op">-</span><span class="st"> </span>T</code></pre></div>
<pre><code>## [1] -1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(T <span class="op">*</span><span class="st"> </span>T) <span class="op">+</span><span class="st"> </span>F</code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>Third, you can coerce numeric elements to valid logicals:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># zero is FALSE</span>
<span class="kw">as.logical</span>(<span class="dv">0</span>)</code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># everything else is TRUE</span>
<span class="kw">as.logical</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">12</span>, <span class="op">-</span><span class="fl">231.3525</span>))</code></pre></div>
<pre><code>## [1] TRUE TRUE TRUE TRUE</code></pre>
<p>Now, you may wonder that use this can possible be?! Well, this way you can perform basic logical operations, such as AND, OR, and XOR (see section “Handy functions that return logicals” below):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># x * y is equivalent to x AND y</span>
<span class="kw">as.logical</span>(T <span class="op">*</span><span class="st"> </span>T)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">as.logical</span>(T <span class="op">*</span><span class="st"> </span>F)</code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">as.logical</span>(F <span class="op">*</span><span class="st"> </span>T)</code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">as.logical</span>(F <span class="op">*</span><span class="st"> </span>F)</code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># x + y is equivalent to x OR y</span>
<span class="kw">as.logical</span>(T <span class="op">+</span><span class="st"> </span>T)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">as.logical</span>(T <span class="op">+</span><span class="st"> </span>F)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">as.logical</span>(F <span class="op">+</span><span class="st"> </span>T)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">as.logical</span>(F <span class="op">+</span><span class="st"> </span>F)</code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># x - y is equivalent to x XOR y (eXclusive OR, either-or)</span>
<span class="kw">as.logical</span>(T <span class="op">-</span><span class="st"> </span>T)</code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">as.logical</span>(T <span class="op">-</span><span class="st"> </span>F)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">as.logical</span>(F <span class="op">-</span><span class="st"> </span>T)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">as.logical</span>(F <span class="op">-</span><span class="st"> </span>F)</code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p> </p></li>
<li><p><code>&quot;factor&quot;</code>, factors are a bit weird. They are used mainly for telling <code>R</code> that a vector represents a categorical variable. For instance, you can be comparing two groups, treatment and control.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create a vector of 15 &quot;control&quot;s and 15 &quot;treatment&quot;s</span>
x &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;control&quot;</span>, <span class="st">&quot;treatment&quot;</span>), <span class="dt">each =</span> <span class="dv">15</span>)
x</code></pre></div>
<pre><code>##  [1] &quot;control&quot;   &quot;control&quot;   &quot;control&quot;   &quot;control&quot;   &quot;control&quot;  
##  [6] &quot;control&quot;   &quot;control&quot;   &quot;control&quot;   &quot;control&quot;   &quot;control&quot;  
## [11] &quot;control&quot;   &quot;control&quot;   &quot;control&quot;   &quot;control&quot;   &quot;control&quot;  
## [16] &quot;treatment&quot; &quot;treatment&quot; &quot;treatment&quot; &quot;treatment&quot; &quot;treatment&quot;
## [21] &quot;treatment&quot; &quot;treatment&quot; &quot;treatment&quot; &quot;treatment&quot; &quot;treatment&quot;
## [26] &quot;treatment&quot; &quot;treatment&quot; &quot;treatment&quot; &quot;treatment&quot; &quot;treatment&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># turn x into a factor</span>
x &lt;-<span class="st"> </span><span class="kw">as.factor</span>(x)
x</code></pre></div>
<pre><code>##  [1] control   control   control   control   control   control   control  
##  [8] control   control   control   control   control   control   control  
## [15] control   treatment treatment treatment treatment treatment treatment
## [22] treatment treatment treatment treatment treatment treatment treatment
## [29] treatment treatment
## Levels: control treatment</code></pre>
<p>The first thing to notice is the line under the last printout that says “<code>Levels: control treatment</code>”. This informs you that <code>x</code> is now a factor with two levels (or, a categorical variable with two categories).</p>
<p>Second thing you should take note of is that the words <code>control</code> and <code>treatment</code> don’t have quotes around them. This is another way <code>R</code> uses to tell you this is a factor.</p>
<p>With factors, it is important to understand how they are represented in <code>R</code>. Despite, what they look like, <strong>under the hood, they are numbers</strong>. A one-level factor is a vector of <code>1</code>s, a two-level factor is a vector of <code>1</code>s and <code>2</code>s, a <em>n</em>-level factor is a vector of <code>1</code>s, <code>2</code>s, <code>3</code>s … <em>n</em>s. The levels, in our case <code>control</code> and <code>treatment</code>, are just labels attached to the <code>1</code>s and <code>2</code>s. Let’s demonstrate this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">typeof</span>(x)</code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># integer is fancy for &quot;whole number&quot;</span>

<span class="co"># we can coerce factors to numeric, thus stripping the labels</span>
<span class="kw">as.numeric</span>(x)</code></pre></div>
<pre><code>##  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># see the labels</span>
<span class="kw">levels</span>(x)</code></pre></div>
<pre><code>## [1] &quot;control&quot;   &quot;treatment&quot;</code></pre>
<p>The labels attached to the numbers in a factor can be whatever. Let’s say that in your raw data file, treatment group is coded as 1 and control group is coded as 0.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create a vector of 15 zeros and 15 ones</span>
x &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">1</span>, <span class="dt">each =</span> <span class="dv">15</span>)
x</code></pre></div>
<pre><code>##  [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># turn x into a factor</span>
x &lt;-<span class="st"> </span><span class="kw">as.factor</span>(x)
x</code></pre></div>
<pre><code>##  [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
## Levels: 0 1</code></pre>
<p>Since <code>x</code> is now a factor with levels <code>0</code> and <code>1</code>, we know that it is stored in <code>R</code> as a vector of <code>1</code>s and <code>2</code>s and <strong>the zeros and ones</strong>, representing the groups, <strong>are only labels</strong>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">as.numeric</span>(x)</code></pre></div>
<pre><code>##  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">levels</span>(x)</code></pre></div>
<pre><code>## [1] &quot;0&quot; &quot;1&quot;</code></pre>
<p>The fact that factors in <code>R</code> are represented as labelled integers has interesting implications some of you have already come across. First, certain functions will coerce factors into numeric vectors which can shake things up. This happened when you used <code>cbind()</code> on a factor with levels <code>0</code> and <code>1</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x</code></pre></div>
<pre><code>##  [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
## Levels: 0 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># let&#39;s bind the first 15 elements and the last 15 elements together as columns</span></code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cbind</span>(x[<span class="dv">1</span><span class="op">:</span><span class="dv">15</span>], x[<span class="dv">16</span><span class="op">:</span><span class="dv">30</span>])</code></pre></div>
<pre><code>##       [,1] [,2]
##  [1,]    1    2
##  [2,]    1    2
##  [3,]    1    2
##  [4,]    1    2
##  [5,]    1    2
##  [ reached getOption(&quot;max.print&quot;) -- omitted 10 rows ]</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># printout truncated to first 5 rows to save space</span></code></pre></div>
<p><code>cbind()</code> binds the vectors you provide into the columns of a matrix. Since matrices (yep, that’s the plural of ‘matrix’; also, more on matrices later) can only contain <code>logical</code>, <code>numeric</code>, and <code>character</code> elements, the <code>cbind()</code> function coerces the elements of the <code>x</code> factor (haha, the X-factor) into <code>numeric</code>, stripping the labels and leaving only <code>1</code>s and <code>2</code>s.</p>
<p>The other two consequences of this labelled numbers system stem from the way the labels are stored. Every <code>R</code> object comes with a list of so called <em>attributes</em> attached to it. These are basically information about the object. For objects of class <code>factor</code>, the attributes include its levels (or the labels attached to the numbers) and class:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attributes</span>(x)</code></pre></div>
<pre><code>## $levels
## [1] &quot;0&quot; &quot;1&quot;
## 
## $class
## [1] &quot;factor&quot;</code></pre>
<p>So the labels are stored separately of the actual elements. This means, that even if you delete some of the numbers, the labels stay the same. Let’s demonstrate this implication on the <code>plot()</code> function. This function is smart enough to know that if you give it a factor it should plot it using a bar chart, and not a histogram or a scatter plot:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(x)</code></pre></div>
<p><img src="saviouR_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>Now, let’s take the first 15 elements of <code>x</code>, which are all <code>0</code>s and plot them:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span>x[<span class="dv">1</span><span class="op">:</span><span class="dv">15</span>]
y</code></pre></div>
<pre><code>##  [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## Levels: 0 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(y)</code></pre></div>
<p><img src="saviouR_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>Even though our new object <code>y</code> only includes <code>0</code>s, the <code>levels</code> attribute still tells <code>R</code> that this is a factor of (at least <em>potentially</em>) two levels: <code>&quot;0&quot;</code> and <code>&quot;1&quot;</code> and so <code>plot()</code> leaves a room for the <code>1</code>s.</p>
<p>The last consequence is directly related to this. Since the levels of an object of class <code>factor</code> are stored as its attributes, any additional values put inside the objects will be invalid and turned into <code>NA</code>s (<code>R</code> will warn us of this). In other words, you <strong>can only add those values that are among the ones produced by <code>levels()</code></strong> to an object of class <code>factor</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># try adding invalid values -4 and 3 to the end of vector x</span>
x[<span class="dv">31</span><span class="op">:</span><span class="dv">32</span>] &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">4</span>, <span class="dv">3</span>)</code></pre></div>
<pre><code>## Warning in `[&lt;-.factor`(`*tmp*`, 31:32, value = c(-4, 3)): invalid factor
## level, NA generated</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x</code></pre></div>
<pre><code>##  [1] 0    0    0    0    0    0    0    0    0    0    0    0    0    0   
## [15] 0    1    1    1    1    1    1    1    1    1    1    1    1    1   
## [29] 1    1    &lt;NA&gt; &lt;NA&gt;
## Levels: 0 1</code></pre>
<p>The only way to add these values to a factor is to first coerce it to <code>numeric</code>, then add the values, and then turn it back into <code>factor</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># coerce x to numeric</span>
x &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(x[<span class="dv">1</span><span class="op">:</span><span class="dv">30</span>])
<span class="kw">class</span>(x)</code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># but remember that 0s and 1s are now 1s and 2s!</span>
x</code></pre></div>
<pre><code>##  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># so subtract 1 to make the values 0s and 1s again</span>
x &lt;-<span class="st"> </span>x <span class="op">-</span><span class="st"> </span><span class="dv">1</span>
<span class="co"># add the new values</span>
x &lt;-<span class="st"> </span><span class="kw">c</span>(x, <span class="op">-</span><span class="dv">4</span>, <span class="dv">3</span>)
<span class="co"># back into fractor</span>
x &lt;-<span class="st"> </span><span class="kw">as.factor</span>(x)
x</code></pre></div>
<pre><code>##  [1] 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1 
## [24] 1  1  1  1  1  1  1  -4 3 
## Levels: -4 0 1 3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># SUCCESS!</span>

<span class="co"># reset</span>
x &lt;-<span class="st"> </span><span class="kw">as.factor</span>(<span class="kw">rep</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">1</span>, <span class="dt">each =</span> <span class="dv">15</span>))
<span class="co"># one-liner</span>
x &lt;-<span class="st"> </span><span class="kw">as.factor</span>(<span class="kw">c</span>(<span class="kw">as.numeric</span>(x[<span class="dv">1</span><span class="op">:</span><span class="dv">30</span>]) <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="op">-</span><span class="dv">4</span>, <span class="dv">3</span>))
x</code></pre></div>
<pre><code>##  [1] 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1 
## [24] 1  1  1  1  1  1  1  -4 3 
## Levels: -4 0 1 3</code></pre>
<p>Told you factors were weird…</p>
<p> </p></li>
<li><p><code>&quot;ordered&quot;</code>, finally, these are the same as factors but, in addition to having levels, these levels are ordered and thus allow comparison (notice the <code>Levels: 0 &lt; 1</code> below):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># coerce x to numeric</span>
x &lt;-<span class="st"> </span><span class="kw">as.ordered</span>(<span class="kw">rep</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">1</span>, <span class="dt">each =</span> <span class="dv">15</span>))
x</code></pre></div>
<pre><code>##  [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
## Levels: 0 &lt; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># we can now compare the levels</span>
x[<span class="dv">1</span>] <span class="op">&lt;</span><span class="st"> </span>x[<span class="dv">30</span>]</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># this is not the case with factors</span>
y &lt;-<span class="st"> </span><span class="kw">as.factor</span>(<span class="kw">rep</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">1</span>, <span class="dt">each =</span> <span class="dv">15</span>))
y[<span class="dv">1</span>] <span class="op">&lt;</span><span class="st"> </span>y[<span class="dv">30</span>]</code></pre></div>
<pre><code>## Warning in Ops.factor(y[1], y[30]): &#39;&lt;&#39; not meaningful for factors</code></pre>
<pre><code>## [1] NA</code></pre>
<p>Objects of class <code>ordered</code> are useful for storing <em>ordinal</em> variables, <em>e.g.,</em> age group.</p>
<p> </p></li>
</ul>
<p>In addition to these five sorts of elements, there are three special wee snowflakes:</p>
<ul>
<li><p><code>NA</code>, stands for “not applicable” and is used for missing data. Unlike other kinds of elements, it can be bound into a vector along with elements of any class.</p></li>
<li><p><code>NaN</code>, stands for “not a number”. It is technically of class <code>numeric</code> but only occurs as the output of invalid mathematical operations, such as dividing zero by zero or taking a square root of a negative number:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">0</span> <span class="op">/</span><span class="st"> </span><span class="dv">0</span></code></pre></div>
<pre><code>## [1] NaN</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sqrt</span>(<span class="op">-</span><span class="dv">12</span>)</code></pre></div>
<pre><code>## Warning in sqrt(-12): NaNs produced</code></pre>
<pre><code>## [1] NaN</code></pre></li>
<li><p><code>Inf</code> (or <code>-Inf</code>), infinity. Reserved for division of a non-zero number by zero (no, it’s not <em>technically</em> right):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">235</span><span class="op">/</span><span class="dv">0</span></code></pre></div>
<pre><code>## [1] Inf</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="op">-</span><span class="fl">85.123</span><span class="op">/</span><span class="dv">0</span></code></pre></div>
<pre><code>## [1] -Inf</code></pre></li>
</ul>
<p> </p>
<div id="data-structures" class="section level3">
<h3>Data structures</h3>
<p>So that’s most of what you need to know about elements. Let’s talk about putting elements together. As mentioned above, elements can be grouped in various data structures. These differ in the ways in which they arrange elements:</p>
<ul>
<li><p><em>vectors</em> arrange elements in a line. they don’t have dimensions and can only contain elements of same class (<em>e.g.,</em> <code>&quot;numeric&quot;</code>, <code>&quot;character&quot;</code>, <code>&quot;logical&quot;</code>).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># a vector</span>
letters[<span class="dv">5</span><span class="op">:</span><span class="dv">15</span>]</code></pre></div>
<pre><code>##  [1] &quot;e&quot; &quot;f&quot; &quot;g&quot; &quot;h&quot; &quot;i&quot; &quot;j&quot; &quot;k&quot; &quot;l&quot; &quot;m&quot; &quot;n&quot; &quot;o&quot;</code></pre>
<p>If you try to force elements of different classes to a single vector, they will all be converted to the <em>most complex</em> class. The order of complexity, from least to most complex, is: <code>logical</code>, <code>numeric</code>, and <code>character</code>. Elements of class <code>factor</code> and <code>ordered</code> cannot be meaningfully bound in a vector with other classes (nor with each other): they either get converted to <code>numeric</code>, <code>character</code> - if you’re lucky - or to <code>NA</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># c(logical, numeric) results in numeric</span>
x &lt;-<span class="st"> </span><span class="kw">c</span>(T, F, <span class="dv">1</span><span class="op">:</span><span class="dv">6</span>)
x</code></pre></div>
<pre><code>## [1] 1 0 1 2 3 4 5 6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(x)</code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># integer is like numeric but only for whole numbers to save computer memory</span>

<span class="co"># adding character results in character</span>
x &lt;-<span class="st"> </span><span class="kw">c</span>(x, <span class="st">&quot;foo&quot;</span>)
<span class="co"># the numbers 1-6 are not numeric any more!</span>
x</code></pre></div>
<pre><code>## [1] &quot;1&quot;   &quot;0&quot;   &quot;1&quot;   &quot;2&quot;   &quot;3&quot;   &quot;4&quot;   &quot;5&quot;   &quot;6&quot;   &quot;foo&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(x)</code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p> </p></li>
<li><p><em>matrices</em> arrange elements in a square/rectangle, <em>i.e.,</em> a two-dimensional arrangement of <em>rows</em> and <em>columns</em>. They can also only accommodate elements of the same class and cannot store attributes of elements. That means, <em>you can’t use them to store (ordered) factors</em>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># a matrix</span>
<span class="kw">matrix</span>(<span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="dt">ncol =</span> <span class="dv">5</span>) <span class="co"># must be square/rectangular</span></code></pre></div>
<pre><code>##           [,1]       [,2]      [,3]     [,4]       [,5]
## [1,] 1.1567767  1.9641274 2.2693010 1.062991 -0.1241066
## [2,] 0.1435369  0.9420612 2.3062937 0.407809  0.2619170
## [3,] 0.6684308  1.4533861 0.9997705 0.610204  0.5355563
## [4,] 1.4685273 -0.5623653 1.0445462 1.376601  2.0203129</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># not suitable for factors</span>
x &lt;-<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rbinom</span>(<span class="dv">10</span>, <span class="dv">1</span>, .<span class="dv">5</span>))
x</code></pre></div>
<pre><code>##  [1] 0 0 0 0 0 1 0 1 1 1
## Levels: 0 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># not factors any more!</span>
<span class="kw">matrix</span>(x, <span class="dt">ncol =</span> <span class="dv">5</span>)</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5]
## [1,] &quot;0&quot;  &quot;0&quot;  &quot;0&quot;  &quot;0&quot;  &quot;1&quot; 
## [2,] &quot;0&quot;  &quot;0&quot;  &quot;1&quot;  &quot;1&quot;  &quot;1&quot;</code></pre>
<p> </p></li>
<li><p><em>lists</em> arrange elements in a collection of vectors or other data structures. Different vectors/structures can be of different lengths and contain elements of different classes. Elements of lists and, by extension, data frames can be accessed using the <code>$</code> operator, provided we gave them names.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># a list</span>
my_list &lt;-<span class="st"> </span><span class="kw">list</span>(
  <span class="co"># 1st element of list is a numeric matrix</span>
  <span class="dt">A =</span> <span class="kw">matrix</span>(<span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="dt">ncol =</span> <span class="dv">5</span>), 
  <span class="co"># 2nd element is a character vector</span>
  <span class="dt">B =</span> letters[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>],
  <span class="co"># third is a data.frame</span>
  <span class="dt">C =</span> <span class="kw">data.frame</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>), <span class="dt">y =</span> LETTERS[<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>])
)

my_list</code></pre></div>
<pre><code>## $A
##             [,1]     [,2]      [,3]     [,4]     [,5]
## [1,] -0.02899778 1.151726 0.9955185 1.001247 1.123871
## [2,]  1.24130052 1.524815 1.9258743 1.034563 2.057456
## [3,]  0.32962175 0.870179 1.3327565 1.250425 1.180549
## [4,]  1.48930141 1.912091 1.6151927 1.648689 2.326943
## 
## $B
## [1] &quot;a&quot; &quot;b&quot; &quot;c&quot; &quot;d&quot; &quot;e&quot;
## 
## $C
##   x y
## 1 1 A
## 2 2 B
## 3 3 C</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># we can use the $ operator to access NAMED elements of lists</span>
my_list<span class="op">$</span>B</code></pre></div>
<pre><code>## [1] &quot;a&quot; &quot;b&quot; &quot;c&quot; &quot;d&quot; &quot;e&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># this is also true for data frames</span>
my_list<span class="op">$</span>C<span class="op">$</span>x</code></pre></div>
<pre><code>## [1] 1 2 3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># but not for vectors or matrices</span>
my_list<span class="op">$</span>A<span class="op">$</span><span class="dv">1</span></code></pre></div>
<pre><code>## Error: &lt;text&gt;:2:11: unexpected numeric constant
## 1: # but not for vectors or matrices
## 2: my_list$A$1
##              ^</code></pre>
<p> </p></li>
<li><p><em>data frames</em> are lists but have an additional constraint: all the vectors of a <code>data.frame</code> must be of the same length. That is the reasons why your datasets are always rectangular.</p></li>
</ul>
<!-- - *arrays* are matrices of *n* number of dimensions. Matrix is always a square/rectangle. An `array` can also be a cube, or a higher dimensional structure. Admittedly, this is tricky to visualise but it is true. -->
<!--     ```{r} -->
<!--     # a 3-dimensional array -->
<!--     array(rnorm(60, 1, 1), dim = c(4, 5, 3)) -->
<!--     ``` -->
<p> </p>
<p>Different data structures are useful for different things but bear in mind that, ultimately, <em>they are all just bunches of elements</em>. This understanding is crucial for working with data.</p>
<p> </p>
</div>
</div>
<div id="there-are-only-two-ways-to-ask-for-elements" class="section level2">
<h2>There are only two ways to ask for elements</h2>
<p>Now that you understand that all data boil down to elements, let’s look at how to ask <code>R</code> for the elements you want.</p>
<p>As the section heading suggests, there are only two ways to do this:</p>
<ol style="list-style-type: decimal">
<li>indices</li>
<li>logical vector</li>
</ol>
<p>Let’s take a closer look at these ways one at a time.</p>
<div id="indices" class="section level3">
<h3>Indices</h3>
<p>The first way to ask for an element is to simply provide the numeric position of the desired element in the structure (vector, list…) in a set of square brackets <code>[]</code> at the end of the object name:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;I&quot;</span>, <span class="st">&quot; &quot;</span>, <span class="st">&quot;l&quot;</span>, <span class="st">&quot;o&quot;</span>, <span class="st">&quot;v&quot;</span>, <span class="st">&quot;e&quot;</span>, <span class="st">&quot; &quot;</span>, <span class="st">&quot;R&quot;</span>)

<span class="co"># get the 6th element</span>
x[<span class="dv">6</span>]</code></pre></div>
<pre><code>## [1] &quot;e&quot;</code></pre>
<p> </p>
<p>To get more than just one element at a time, you need to provide <em>a vector</em> of indices. For instance, to get the elements 3-6 of <code>x</code>, we can do:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x[<span class="dv">3</span><span class="op">:</span><span class="dv">6</span>]</code></pre></div>
<pre><code>## [1] &quot;l&quot; &quot;o&quot; &quot;v&quot; &quot;e&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># equivalent to</span>
x[<span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>)]</code></pre></div>
<pre><code>## [1] &quot;l&quot; &quot;o&quot; &quot;v&quot; &quot;e&quot;</code></pre>
<p> </p>
<p>Remember that some structures can contain as their elements other structures. For example asking for the first element of <code>my_list</code> will return:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">my_list[<span class="dv">1</span>]</code></pre></div>
<pre><code>## $A
##             [,1]     [,2]      [,3]     [,4]     [,5]
## [1,] -0.02899778 1.151726 0.9955185 1.001247 1.123871
## [2,]  1.24130052 1.524815 1.9258743 1.034563 2.057456
## [3,]  0.32962175 0.870179 1.3327565 1.250425 1.180549
## [4,]  1.48930141 1.912091 1.6151927 1.648689 2.326943</code></pre>
<p> </p>
<p>The <code>$A</code> at the top of the output indicates that we have accessed the element <code>A</code> of <code>my_list</code> but not really accessed the matrix itself. Thus, at this stage, we wouldn’t be able to ask for it’s elements. To access the matrix contained in <code>my_list$A</code>, we need to write either exactly that, or use double brackets:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">my_list[[<span class="dv">1</span>]]</code></pre></div>
<pre><code>##             [,1]     [,2]      [,3]     [,4]     [,5]
## [1,] -0.02899778 1.151726 0.9955185 1.001247 1.123871
## [2,]  1.24130052 1.524815 1.9258743 1.034563 2.057456
## [3,]  0.32962175 0.870179 1.3327565 1.250425 1.180549
## [4,]  1.48930141 1.912091 1.6151927 1.648689 2.326943</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># with the $A now gone from output, we can access the matrix itself</span>
my_list[[<span class="dv">1</span>]][<span class="dv">1</span>]</code></pre></div>
<pre><code>## [1] -0.02899778</code></pre>
<p> </p>
<p>As discussed above, some data structures are dimensionless (vectors, lists), while others are arranged in <em>n</em>-dimensional rectangles (where <em>n</em> &gt; 1). When indexing/subsetting elements of dimensional structures, we need to provide coordinates of the elements for each dimension. This is done by providing <em>n</em> numbers or vectors in the <code>[]</code>s separated by a comma.</p>
<p>A matrix, for instance has 2 dimensions, rows and columns. The first number/vector in the <code>[]</code>s represents rows and the second columns. Leaving either position blank will return all rows/columns:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat &lt;-<span class="st"> </span><span class="kw">matrix</span>(LETTERS[<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>], <span class="dt">ncol =</span> <span class="dv">5</span>)
mat</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5]
## [1,] &quot;A&quot;  &quot;E&quot;  &quot;I&quot;  &quot;M&quot;  &quot;Q&quot; 
## [2,] &quot;B&quot;  &quot;F&quot;  &quot;J&quot;  &quot;N&quot;  &quot;R&quot; 
## [3,] &quot;C&quot;  &quot;G&quot;  &quot;K&quot;  &quot;O&quot;  &quot;S&quot; 
## [4,] &quot;D&quot;  &quot;H&quot;  &quot;L&quot;  &quot;P&quot;  &quot;T&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># blank spaces technically not needed but improve code readability</span>
mat[<span class="dv">1</span>, ] <span class="co"># first row</span></code></pre></div>
<pre><code>## [1] &quot;A&quot; &quot;E&quot; &quot;I&quot; &quot;M&quot; &quot;Q&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat[ , <span class="dv">1</span>] <span class="co"># first column</span></code></pre></div>
<pre><code>## [1] &quot;A&quot; &quot;B&quot; &quot;C&quot; &quot;D&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat[<span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">4</span>), ] <span class="co"># rows 2 and 4, notice the c()</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5]
## [1,] &quot;B&quot;  &quot;F&quot;  &quot;J&quot;  &quot;N&quot;  &quot;R&quot; 
## [2,] &quot;D&quot;  &quot;H&quot;  &quot;L&quot;  &quot;P&quot;  &quot;T&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat[<span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">4</span>), <span class="dv">1</span><span class="op">:</span><span class="dv">3</span>] <span class="co"># elements 2 and 4 of columns 1-3</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,] &quot;B&quot;  &quot;F&quot;  &quot;J&quot; 
## [2,] &quot;D&quot;  &quot;H&quot;  &quot;L&quot;</code></pre>
<p> </p>
<p>To get the full matrix, we simply type its name. However, you can think of the same operation as asking for <em>all rows</em> and <em>all columns</em> of the matrix:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat[ , ] <span class="co"># all rows, all columns</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5]
## [1,] &quot;A&quot;  &quot;E&quot;  &quot;I&quot;  &quot;M&quot;  &quot;Q&quot; 
## [2,] &quot;B&quot;  &quot;F&quot;  &quot;J&quot;  &quot;N&quot;  &quot;R&quot; 
## [3,] &quot;C&quot;  &quot;G&quot;  &quot;K&quot;  &quot;O&quot;  &quot;S&quot; 
## [4,] &quot;D&quot;  &quot;H&quot;  &quot;L&quot;  &quot;P&quot;  &quot;T&quot;</code></pre>
<p> </p>
<p>The same is the case with data frames:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">id =</span> LETTERS[<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>],
                <span class="dt">group =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;Control&quot;</span>, <span class="st">&quot;Treatment&quot;</span>), <span class="dt">each =</span> <span class="dv">3</span>),
                <span class="dt">score =</span> <span class="kw">rnorm</span>(<span class="dv">6</span>, <span class="dv">100</span>, <span class="dv">20</span>))
df</code></pre></div>
<pre><code>##   id     group     score
## 1  A   Control 118.30509
## 2  B   Control 125.87896
## 3  C   Control  53.90958
## 4  D Treatment 133.67045
## 5  E Treatment 102.53817
## 6  F Treatment 111.34231</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df[<span class="dv">1</span>, ] <span class="co"># first row</span></code></pre></div>
<pre><code>##   id   group    score
## 1  A Control 118.3051</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df[<span class="dv">4</span><span class="op">:</span><span class="dv">6</span>, <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>)]</code></pre></div>
<pre><code>##   id    score
## 4  D 133.6704
## 5  E 102.5382
## 6  F 111.3423</code></pre>
<p> </p>
<!-- This `[row, column]` system can be extended to multiple dimensions. As we said above, arrays can have *n* dimensions and so we need *n* positions in the `[]`s to ask for elements: -->
<!-- ```{r} -->
<!-- # a 3-dimensional array -->
<!-- arr_3d <- array(rnorm(60, 1, 1), dim = c(4, 5, 3)) -->
<!-- arr_3d -->
<!-- arr_3d[1, , ] # first row-slice -->
<!-- arr_3d[1, 2:4, 3] # elements in row 1 of columns 2-4 in the 3rd space of the 3rd dimension -->
<!-- ``` -->
<!-- &nbsp; -->
<!-- While 3D arrays can still be visualised as cubes (or rectangular cuboids), higher-*n*-dimensional arrays are trickier. For instance, a 4D array would have a separate cuboid in every position of `[x,`&nbsp;`,`&nbsp;`,`&nbsp;`]`, `[`&nbsp;`,`&nbsp;`y,`&nbsp;`,`&nbsp;`]`, `[&nbsp;`,`&nbsp;`,`&nbsp;`z,`&nbsp;`]`, and `[`&nbsp;`,`&nbsp;`,`&nbsp;`,`&nbsp;`q]`. You are not likely to come across 3+ dimensional arrays but it is good to understand that, in principle, they are just extensions of 2D arrays (matrices) and thus same rules apply. -->
<p><strong>Take home message: </strong>when using indices to ask for elements, remember that to request more than one, you need to give a <strong>vector of indices</strong> (<em>i.e.,</em> numbers bound in a <code>c()</code>). Also remember that some data structures need you to specify dimensions <strong>separated by a comma</strong> (most often just rows and columns for matrices and data frames).</p>
<p> </p>
</div>
<div id="logical-vectors" class="section level3">
<h3>Logical vectors</h3>
<p>The other way of asking for elements is by putting a vector of logical (AKA Boolean) values in the <code>[]</code>s. An important requirement here is that the vector <strong>must be the same length as the one being subsetted</strong>. So, for a vector with three elements, we need to provide three logical values, <code>TRUE</code> for “<em>I want this one</em>” and <code>FALSE</code> for “<em>I don’t want this one</em>”. Let’s demonstrate this on the same vector we used for indices:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;I&quot;</span>, <span class="st">&quot; &quot;</span>, <span class="st">&quot;l&quot;</span>, <span class="st">&quot;o&quot;</span>, <span class="st">&quot;v&quot;</span>, <span class="st">&quot;e&quot;</span>, <span class="st">&quot; &quot;</span>, <span class="st">&quot;R&quot;</span>)

<span class="co"># get the 6th element</span>
x[<span class="kw">c</span>(F, F, F, F, F, T, F, F)]</code></pre></div>
<pre><code>## [1] &quot;e&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#get elements 3-6</span>
x[<span class="kw">c</span>(F, F, T, T, T, T, F, F)]</code></pre></div>
<pre><code>## [1] &quot;l&quot; &quot;o&quot; &quot;v&quot; &quot;e&quot;</code></pre>
<p> </p>
<p>All the other principles we talked about regarding indexing apply also to logical vectors. Note also, that higher 2D structures need a <em>logical row vector</em> and a <em>logical column vector</em>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># recall our mat</span>
mat</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5]
## [1,] &quot;A&quot;  &quot;E&quot;  &quot;I&quot;  &quot;M&quot;  &quot;Q&quot; 
## [2,] &quot;B&quot;  &quot;F&quot;  &quot;J&quot;  &quot;N&quot;  &quot;R&quot; 
## [3,] &quot;C&quot;  &quot;G&quot;  &quot;K&quot;  &quot;O&quot;  &quot;S&quot; 
## [4,] &quot;D&quot;  &quot;H&quot;  &quot;L&quot;  &quot;P&quot;  &quot;T&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># rows 2 and 4</span>
mat[<span class="kw">c</span>(T, F, T, F), ]</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5]
## [1,] &quot;A&quot;  &quot;E&quot;  &quot;I&quot;  &quot;M&quot;  &quot;Q&quot; 
## [2,] &quot;C&quot;  &quot;G&quot;  &quot;K&quot;  &quot;O&quot;  &quot;S&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># element 4 of rows 1 and 2</span>
mat[<span class="kw">c</span>(F, F, F, T), <span class="kw">c</span>(T, T, F, F, F)]</code></pre></div>
<pre><code>## [1] &quot;D&quot; &quot;H&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># you can even COMBINE the two ways!</span>
mat[<span class="dv">4</span>, <span class="kw">c</span>(T, T, F, F, F)]</code></pre></div>
<pre><code>## [1] &quot;D&quot; &quot;H&quot;</code></pre>
<p> </p>
<p>And as if vectors weren’t enough, you can even use matrices of logical values to subset matrices and data frames:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat_logic &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="kw">rep</span>(<span class="kw">c</span>(F, T), <span class="dt">each =</span> <span class="dv">3</span>), <span class="kw">rep</span>(F, <span class="dv">9</span>), <span class="kw">c</span>(T, T, T)), <span class="dt">ncol =</span> <span class="dv">3</span>)
mat_logic</code></pre></div>
<pre><code>##       [,1]  [,2]  [,3]
## [1,] FALSE FALSE FALSE
## [2,] FALSE FALSE FALSE
## [3,] FALSE FALSE FALSE
## [4,]  TRUE FALSE  TRUE
## [5,]  TRUE FALSE  TRUE
## [6,]  TRUE FALSE  TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df[mat_logic]</code></pre></div>
<pre><code>## [1] &quot;D&quot;         &quot;E&quot;         &quot;F&quot;         &quot;133.67045&quot; &quot;102.53817&quot; &quot;111.34231&quot;</code></pre>
<p> </p>
<p>Notice, however, that the output is a vector so two things happened: first, the rectangular structure has been erased and second, since vectors can only contain elements of the same class (see above), the numbers got converted into character strings (hence the <code>&quot;&quot;</code>s). Nevertheless, this method of subsetting using logical matrices can be useful for replacing several values in different rows and columns with another value:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># replace with NAs</span>
df[mat_logic] &lt;-<span class="st"> </span><span class="ot">NA</span>
df</code></pre></div>
<pre><code>##     id     group     score
## 1    A   Control 118.30509
## 2    B   Control 125.87896
## 3    C   Control  53.90958
## 4 &lt;NA&gt; Treatment        NA
## 5 &lt;NA&gt; Treatment        NA
## 6 &lt;NA&gt; Treatment        NA</code></pre>
<p> </p>
<p>To use a different example, take the function <code>lower.tri()</code>. It can be used to subset a matrix in order to get the lower triangle (with or without the diagonal). Consider matrix <code>mat2</code> which has <code>&quot;L&quot;</code>s in its lower triangle, <code>&quot;U&quot;</code>s in its upper triangle, and <code>&quot;D&quot;</code>s on the diagonal:</p>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,] &quot;D&quot;  &quot;U&quot;  &quot;U&quot;  &quot;U&quot; 
## [2,] &quot;L&quot;  &quot;D&quot;  &quot;U&quot;  &quot;U&quot; 
## [3,] &quot;L&quot;  &quot;L&quot;  &quot;D&quot;  &quot;U&quot; 
## [4,] &quot;L&quot;  &quot;L&quot;  &quot;L&quot;  &quot;D&quot;</code></pre>
<p> </p>
<p>Let’s use <code>lower.tri()</code> to ask for the elements in its lower triangle:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat2[<span class="kw">lower.tri</span>(mat2)]</code></pre></div>
<pre><code>## [1] &quot;L&quot; &quot;L&quot; &quot;L&quot; &quot;L&quot; &quot;L&quot; &quot;L&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># we got only &quot;L&quot;s, good!</span></code></pre></div>
<p> </p>
<p>Adding the <code>, diag = T</code> will return the lower triangle along with the diagonal:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat2[<span class="kw">lower.tri</span>(mat2, <span class="dt">diag =</span> T)]</code></pre></div>
<pre><code>##  [1] &quot;D&quot; &quot;L&quot; &quot;L&quot; &quot;L&quot; &quot;D&quot; &quot;L&quot; &quot;L&quot; &quot;D&quot; &quot;L&quot; &quot;D&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># we got only &quot;L&quot;s and &quot;D&quot;s</span></code></pre></div>
<p> </p>
<p>So what does the function actually do? What is this sorcery? Let’s look at the output of the function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lower.tri</span>(mat2)</code></pre></div>
<pre><code>##       [,1]  [,2]  [,3]  [,4]
## [1,] FALSE FALSE FALSE FALSE
## [2,]  TRUE FALSE FALSE FALSE
## [3,]  TRUE  TRUE FALSE FALSE
## [4,]  TRUE  TRUE  TRUE FALSE</code></pre>
<p>So the function produces a matrix of logicals, the same size as out <code>mat2</code>, with <code>TRUE</code>s in the lower triangle and <code>FALSE</code>s elsewhere. What we did above is simply use this matrix to subset <code>mat2[]</code>.</p>
<p>If you’re curious how the function produces the logical matrix then, first of all, that’s great, keep it up and second, you can look at the code wrapped in the <code>lower.tri</code> object (since functions are only objects of a special kind with code inside instead of data):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lower.tri

<span class="cf">function</span> (x, <span class="dt">diag =</span> <span class="ot">FALSE</span>) 
{
    x &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(x)
    <span class="cf">if</span> (diag) 
        <span class="kw">row</span>(x) <span class="op">&gt;=</span><span class="st"> </span><span class="kw">col</span>(x)
    <span class="cf">else</span> <span class="kw">row</span>(x) <span class="op">&gt;</span><span class="st"> </span><span class="kw">col</span>(x)
}
<span class="op">&lt;</span>bytecode<span class="op">:</span><span class="st"> </span><span class="dv">0x0000000015a39ab0</span><span class="op">&gt;</span>
<span class="er">&lt;</span>environment<span class="op">:</span><span class="st"> </span>namespace<span class="op">:</span>base<span class="op">&gt;</span></code></pre></div>
<p>Right, let’s see. If we set the <code>diag</code> argument to <code>TRUE</code> the function returns <code>row(x) &gt;= col(x)</code>. If we leave it set to <code>FALSE</code> (default), it returns <code>row(x) &gt; col(x)</code>. Let’s substitute <code>x</code> for our <code>mat2</code> and try it out:</p>
<p> </p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">row</span>(mat2)</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    1    1    1
## [2,]    2    2    2    2
## [3,]    3    3    3    3
## [4,]    4    4    4    4</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">col</span>(mat2)</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    2    3    4
## [2,]    1    2    3    4
## [3,]    1    2    3    4
## [4,]    1    2    3    4</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># diag = TRUE case</span>
<span class="kw">row</span>(mat2) <span class="op">&gt;=</span><span class="st"> </span><span class="kw">col</span>(mat2)</code></pre></div>
<pre><code>##      [,1]  [,2]  [,3]  [,4]
## [1,] TRUE FALSE FALSE FALSE
## [2,] TRUE  TRUE FALSE FALSE
## [3,] TRUE  TRUE  TRUE FALSE
## [4,] TRUE  TRUE  TRUE  TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># use it for subsetting mat2</span>
mat2[<span class="kw">row</span>(mat2) <span class="op">&gt;=</span><span class="st"> </span><span class="kw">col</span>(mat2)]</code></pre></div>
<pre><code>##  [1] &quot;D&quot; &quot;L&quot; &quot;L&quot; &quot;L&quot; &quot;D&quot; &quot;L&quot; &quot;L&quot; &quot;D&quot; &quot;L&quot; &quot;D&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># diag = FALSE case</span>
<span class="kw">row</span>(mat2) <span class="op">&gt;</span><span class="st"> </span><span class="kw">col</span>(mat2)</code></pre></div>
<pre><code>##       [,1]  [,2]  [,3]  [,4]
## [1,] FALSE FALSE FALSE FALSE
## [2,]  TRUE FALSE FALSE FALSE
## [3,]  TRUE  TRUE FALSE FALSE
## [4,]  TRUE  TRUE  TRUE FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat2[<span class="kw">row</span>(mat2) <span class="op">&gt;</span><span class="st"> </span><span class="kw">col</span>(mat2)]</code></pre></div>
<pre><code>## [1] &quot;L&quot; &quot;L&quot; &quot;L&quot; &quot;L&quot; &quot;L&quot; &quot;L&quot;</code></pre>
<p> </p>
<p><strong>MAGIC!</strong></p>
<p> </p>
<p><strong>Take home message: </strong>When subsetting using logical vectors, the vectors must be <strong>the same length</strong> as the vectors you are subsetting. The same goes for logical matrices: they must be <strong>the same size</strong> as the matrix/data frame you are subsetting.</p>
</div>
<div id="complementary-subsetting" class="section level3">
<h3>Complementary subsetting</h3>
<p>Both of the aforementioned ways of asking for subsets of data can be inverted. For indices, you can simply put a <code>-</code> sign before the vector:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># elements 3-6 of x</span>
x[<span class="dv">3</span><span class="op">:</span><span class="dv">6</span>]</code></pre></div>
<pre><code>## [1] &quot;l&quot; &quot;o&quot; &quot;v&quot; &quot;e&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># invert the selection</span>
x[<span class="op">-</span>(<span class="dv">3</span><span class="op">:</span><span class="dv">6</span>)]</code></pre></div>
<pre><code>## [1] &quot;I&quot; &quot; &quot; &quot; &quot; &quot;R&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#equivalent to </span>
x[<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">7</span>, <span class="dv">8</span>)]</code></pre></div>
<pre><code>## [1] &quot;I&quot; &quot; &quot; &quot; &quot; &quot;R&quot;</code></pre>
<p> </p>
<p>For logical subsetting, you need to <em>negate</em> the values. That is done using the logical negation operator ‘<code>!</code>’ (AKA “not”):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span>T
y</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># negation</span>
<span class="op">!</span>y</code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># also works for vectors and matrices</span>
mat_logic</code></pre></div>
<pre><code>##       [,1]  [,2]  [,3]
## [1,] FALSE FALSE FALSE
## [2,] FALSE FALSE FALSE
## [3,] FALSE FALSE FALSE
## [4,]  TRUE FALSE  TRUE
## [5,]  TRUE FALSE  TRUE
## [6,]  TRUE FALSE  TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="op">!</span>mat_logic</code></pre></div>
<pre><code>##       [,1] [,2]  [,3]
## [1,]  TRUE TRUE  TRUE
## [2,]  TRUE TRUE  TRUE
## [3,]  TRUE TRUE  TRUE
## [4,] FALSE TRUE FALSE
## [5,] FALSE TRUE FALSE
## [6,] FALSE TRUE FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df[<span class="op">!</span>mat_logic]</code></pre></div>
<pre><code>##  [1] &quot;A&quot;         &quot;B&quot;         &quot;C&quot;         &quot;Control&quot;   &quot;Control&quot;  
##  [6] &quot;Control&quot;   &quot;Treatment&quot; &quot;Treatment&quot; &quot;Treatment&quot; &quot;118.30509&quot;
## [11] &quot;125.87896&quot; &quot; 53.90958&quot;</code></pre>
<p> </p>
<p><strong>Bear in mind that all data cleaning and transforming ultimately boils down to using either or both of these two ways of subsetting elements!</strong></p>
</div>
</div>
<div id="think-of-commands-in-terms-of-their-output" class="section level2">
<h2>Think of commands in terms of their output</h2>
<p>In order to be able to manipulate your data, you need to understand that any chunk of code is just a formal representation of what the code is supposed to be doing, <em>i.e.,</em> its output. That means that you are free to put code inside <code>[]</code>s but only so long as the output of the code is <strong>either a numeric vector</strong> (of valid values - you cannot ask for <code>x[c(3, 6, 7)]</code> if <code>x</code> has only six elements) <strong>or a logical vector/matrix of the same length/size</strong> as the object that is being subsetted. Put any other code inside <code>[]</code>s and <code>R</code> will return an error (or even worse, quietly produce some unexpected behaviour)!</p>
<p>So the final point we would like to stress is that you need to…</p>
</div>
<div id="know-what-to-expect" class="section level2">
<h2>Know what to expect</h2>
<p>You should not be surprised by the outcome of <code>R</code>. If you are, that means you do not entirely understand what you asked <code>R</code> to do. A good way to practice this understanding is to tell yourself what form of output and what values you expect a command to return.</p>
<p>For instance, in the code above, we did <code>x[-(3:6)]</code>. Ask yourself what does the <code>-(3:6)</code> return. How and why is it different from <code>-3:6</code>? What will happen if you do <code>x[-3:6]</code>?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="op">-</span>(<span class="dv">3</span><span class="op">:</span><span class="dv">6</span>)</code></pre></div>
<pre><code>## [1] -3 -4 -5 -6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="op">-</span><span class="dv">3</span><span class="op">:</span><span class="dv">6</span></code></pre></div>
<pre><code>##  [1] -3 -2 -1  0  1  2  3  4  5  6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x[<span class="op">-</span><span class="dv">3</span><span class="op">:</span><span class="dv">6</span>]</code></pre></div>
<pre><code>## Error in x[-3:6]: only 0&#39;s may be mixed with negative subscripts</code></pre>
<p>If any of the output above surprised you, try to understand why. What were your expectations? Do you now, having seen the actual output, understand what those commands do?</p>
<p>Some of you were wondering why, when replacing values in column 1 of matrix <code>mat</code> that are larger than, say, 2 with <code>NA</code>s, you had to specify the column several times, <em>e.g.</em>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat[mat[ , <span class="dv">1</span>] <span class="op">&gt;</span><span class="st"> </span><span class="dv">2</span>, <span class="dv">1</span>] &lt;-<span class="st"> </span><span class="ot">NA</span>

## 2 instances of mat[ , 1] in total:
<span class="co"># 1. outer</span>
mat[..., <span class="dv">1</span>]
<span class="co"># 2. comparison</span>
mat[ , <span class="dv">1</span>] <span class="op">&gt;</span><span class="st"> </span>...</code></pre></div>
<p>Let’s consider matrix <code>mat</code>:</p>
<pre><code>##            [,1]        [,2]       [,3]       [,4]       [,5]       [,6]
## [1,] -0.6112542 -0.01742920 -0.5529373 -0.4981059 -1.0391458 -0.7287290
## [2,]  0.1039312  0.34878391  0.9543797  1.3075571 -0.1741269 -0.1985031
## [3,]  2.4322500 -0.08962998 -0.8534926  0.2307777  1.0808634  1.5590538
## [4,]  0.7135428  0.78263570 -0.4057469  0.1477772 -0.7258886 -0.3941848
## [5,]  0.1330136 -0.08989620  0.9695277  0.9149179  0.1263356 -1.2034913</code></pre>
<p> </p>
<p>and think of the command in terms of the expected outcome of its constituent elements. The logical operator ‘<code>&gt;</code>’ <em>returns a logical vector</em> corresponding to the answer to the question “is the value to the left of the operator larger than that to the right of the operator?” The answer can only be <code>TRUE</code> or <code>FALSE</code>. So <code>mat[ , 1] &gt; 2</code> will return:</p>
<pre><code>## [1] FALSE FALSE  TRUE FALSE FALSE</code></pre>
<p><strong>There is no way of knowing that these values correspond to the 1<sup>st</sup> column of <code>mat</code> just from the output alone.</strong> That information has been lost.</p>
<p>This means that, if we type <code>mat[mat[ , 1] &gt; 2, ]</code>, we are passing a vector of <code>T/F</code>s to the row position of the <code>[]</code>s. The logical vector itself contains no information about it coming from a comparison of the 1<sup>st</sup> row of <code>mat</code> to the value of <code>2</code>. So <code>R</code> can only understand the command as <code>mat[c(FALSE, FALSE, TRUE, FALSE, FALSE), ]</code> and will try to recycle the vector <code>FALSE, FALSE, TRUE, FALSE, FALSE</code> for <strong>every column</strong> of <code>mat</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat[mat[ , <span class="dv">1</span>] <span class="op">&gt;</span><span class="st"> </span><span class="dv">2</span>, ]</code></pre></div>
<pre><code>## [1]  2.43225000 -0.08962998 -0.85349258  0.23077771  1.08086341  1.55905375</code></pre>
<p> </p>
<p>If you want to only extract values from <code>mat[ , 1]</code> that correspond to the <code>TRUE</code>s, you must tell <code>R</code> that, hence the apparent (but not actual) repetition in <code>mat[mat[ , 1] &gt; 2, 1]</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat[mat[ , <span class="dv">1</span>] <span class="op">&gt;</span><span class="st"> </span><span class="dv">2</span>, <span class="dv">1</span>] &lt;-<span class="st"> </span><span class="ot">NA</span>
mat</code></pre></div>
<pre><code>##            [,1]        [,2]       [,3]       [,4]       [,5]       [,6]
## [1,] -0.6112542 -0.01742920 -0.5529373 -0.4981059 -1.0391458 -0.7287290
## [2,]  0.1039312  0.34878391  0.9543797  1.3075571 -0.1741269 -0.1985031
## [3,]         NA -0.08962998 -0.8534926  0.2307777  1.0808634  1.5590538
## [4,]  0.7135428  0.78263570 -0.4057469  0.1477772 -0.7258886 -0.3941848
## [5,]  0.1330136 -0.08989620  0.9695277  0.9149179  0.1263356 -1.2034913</code></pre>
<p> </p>
<p>This feature might strike some as redundant but it is actually the only sensible way. The fact that <code>R</code> is not trying to guess what columns of the data you are requesting from the syntax of the code used for subsetting the rows (and <em>vice versa</em>) means, that you can subset matrix <strong>A</strong> based on some comparison of matrix <strong>B</strong> (provided they are the same size). Or, you can replace values of <code>mat[</code> <code>,</code> <code>3]</code> based on some condition concerning <code>mat[</code> <code>,</code> <code>2]</code>. That can be very handy!</p>
<p>It may take some time to get the hang of this but we cannot overstate the importance of knowing what the expected outcome of your commands is.</p>
</div>
</div>
<div id="putting-it-all-together" class="section level1">
<h1>Putting it all together</h1>
<p>Now that we’ve discussed the key principles of talking to computers, let’s solidify this new understanding using an example you will often encounter. Let’s load the data from the healthIQ.csv file (Lab 6). According to our second principle, <em>if we want to keep it for later, we must put it in an object</em>. Let’s call this object <code>df</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;week_6_glm1_correlation/healthIQ.csv&quot;</span>)
<span class="kw">head</span>(df)</code></pre></div>
<pre><code>##   ID Agegroup ExGroup        IQ
## 1  1        1       1  89.95680
## 2  2        1       1 104.35860
## 3  3        1       1  98.56626
## 4  4        1       1 118.60979
## 5  5        1       1 116.72901
## 6  6        1     999 107.97970</code></pre>
<p>Yep, that looks about right.</p>
<p> </p>
<p>Now, let’s replace all values of IQ that are further than <span class="math inline">\(\pm 2\)</span> standard deviations from the mean of the variable with <code>NA</code>s.</p>
<p>First, we need to <strong>think</strong> conceptually and <strong>algorithmically</strong> about this task: What does it actually mean for a data point to be further than <span class="math inline">\(\pm 2\)</span> standard deviations from the mean? Well, that means that if <span class="math inline">\(Mean(x) = 100\)</span> and <span class="math inline">\(std.dev(x) = 15.34\)</span>, we want to select all data points (elements of <code>x</code>) that are <strong>either smaller than</strong> <span class="math inline">\(100 - 2 \times 15.34 = 69.32\)</span> <strong>or larger than</strong> <span class="math inline">\(100 + 2 \times 15.34 = 130.68\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># let&#39;s start by calculating the mean</span>
<span class="co"># (the outer brackets are there for instant printing)</span>
<span class="co"># na.rm = T is there to disregard any potential NAs</span>
(m_iq &lt;-<span class="st"> </span><span class="kw">mean</span>(df<span class="op">$</span>IQ, <span class="dt">na.rm =</span> T))</code></pre></div>
<pre><code>## [1] 99.99622</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># now let&#39;s get the standard deviation</span>
(sd_iq &lt;-<span class="st"> </span><span class="kw">sd</span>(df<span class="op">$</span>IQ, <span class="dt">na.rm =</span> T))</code></pre></div>
<pre><code>## [1] 15.34238</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># now calculate the lower and upper critical values</span>
(crit_lo &lt;-<span class="st"> </span>m_iq <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>sd_iq)</code></pre></div>
<pre><code>## [1] 69.31145</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(crit_hi &lt;-<span class="st"> </span>m_iq <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>sd_iq)</code></pre></div>
<pre><code>## [1] 130.681</code></pre>
<p> </p>
<p>This tells us that we want to replace all elements of <code>df$IQ</code> that are smaller than 69.31 or larger than 130.68. Let’s do this!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># let&#39;s get a logical vector with TRUE where IQ is larger then crit_hi and</span>
<span class="co"># FALSE otherwise</span>
condition_hi &lt;-<span class="st"> </span>df<span class="op">$</span>IQ <span class="op">&gt;</span><span class="st"> </span>crit_hi
<span class="co"># same for IQ smaller than crit_lo</span>
condition_lo &lt;-<span class="st"> </span>df<span class="op">$</span>IQ <span class="op">&lt;</span><span class="st"> </span>crit_lo</code></pre></div>
<p> </p>
<p>Since we want all data points that fulfil <em>either</em> condition, we need to use the OR operator. The <code>R</code> symbol for OR is a vertical bar “<code>|</code>” (see bottom of document for more info on logical operators):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create logical vector with TRUE if df$IQ meets</span>
<span class="co"># condition_lo OR condition_hi</span>
condition &lt;-<span class="st"> </span>condition_lo <span class="op">|</span><span class="st"> </span>condition_hi</code></pre></div>
<p> </p>
<p>Next, we want to replace the values that fulfil the condition with <code>NA</code>s, in other words, we want to do a little subsetting. As we’ve discussed, there are <strong>only two ways</strong> of doing this: indices and logicals. If we heed principles 5 and 6, <strong>think of our code in terms of its output</strong> and <strong>know what to expect</strong>, we will understand that the code above returns a <em>logical vector</em> of <code>length(df$IQ)</code> with <code>TRUE</code>s in places corresponding to positions of those elements of <code>df$IQ</code> that are further than <span class="math inline">\(\pm 2SD\)</span> from the mean and <code>FALSE</code>s elsewhere. Let’s check:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">condition</code></pre></div>
<pre><code>##   [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE
##  [12] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [23] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [34] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [45] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [56] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [67] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE
##  [78] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [89] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [100] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [111] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [122]  TRUE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [133]  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [144] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [155] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [166] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE
## [177] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [188] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [199] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [210] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [221] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [232] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [243] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
## [254] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [265] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE
## [276] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [287] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [298] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [309] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [320] FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># now let&#39;s use this object to index out elements of df$IQ which</span>
<span class="co"># fulfil the condition</span>
df<span class="op">$</span>IQ[condition]</code></pre></div>
<pre><code>##  [1]  20.00000 132.35251  58.85790 132.98465  58.24403 135.92026 132.92835
##  [8] 130.98682  61.39313  67.00030 135.09655  55.77873  68.37715</code></pre>
<p> </p>
<p>Finally, we want to replace these values with <code>NA</code>s. That’s easy right? All we need to do is to put this vector into <code>[]</code>s next to <code>df$IQ</code> (or <code>df[[&quot;IQ&quot;]]</code>, <code>df[ , &quot;IQ&quot;]</code>, <code>df[ , 4]</code>, or different still, <code>df[[4]]</code>) and assign the value of <code>NA</code> to them:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df<span class="op">$</span>IQ[condition] &lt;-<span class="st"> </span><span class="ot">NA</span>
<span class="co"># see the result (only rows with NAs in IQ)</span>
df[<span class="kw">is.na</span>(df[[<span class="dv">4</span>]]), ]</code></pre></div>
<pre><code>##      ID Agegroup ExGroup IQ
## 10   10        1       1 NA
## 11   11        1       1 NA
## 71   71        1       2 NA
## 77   77        1       2 NA
## 122 122        1       2 NA
## 125 125        1       2 NA
## 133 133        1       2 NA
## 135 135        1       2 NA
## 171 171        2       1 NA
## 212 212        2       1 NA
## 247 247        2       2 NA
## 270 270        2       2 NA
## 288 288        2       2 NA</code></pre>
<p><strong>SUCCESS!</strong></p>
<p>We replaced outlying values of <code>IQ</code> with <code>NA</code>s. Or, to be pedantic (and that is a virtue when talking to computers), we took the labels identifying the elements <code>mat[c(FALSE, FALSE, TRUE, FALSE, FALSE), ]</code> of the <code>df$IQ</code> vector, put those labels on a bunch of <code>NA</code>s and burned the original elements. All that because <strong>you cannot <em>really</em> change an <code>R</code> object</strong>.</p>
<p> </p>
<div id="are-there-quicker-ways" class="section level2">
<h2>Are there quicker ways?</h2>
<p>You might be wondering if there are other ways of achieving the same outcome, perhaps with fewer steps. Well, aren’t you lucky, there are indeed! For instance, you can put all of the code above in a single command, like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># IQ[(IQ is smaller than mean - 2SD) OR (IQ is larger than mean + 2SD)] &lt;- NA</span>
df<span class="op">$</span>IQ[(df<span class="op">$</span>IQ <span class="op">&lt;</span><span class="st"> </span><span class="kw">mean</span>(df<span class="op">$</span>IQ, <span class="dt">na.rm =</span> T) <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">sd</span>(df<span class="op">$</span>IQ, <span class="dt">na.rm =</span> T)) <span class="op">|</span>
<span class="st">        </span>(df<span class="op">$</span>IQ <span class="op">&gt;</span><span class="st"> </span><span class="kw">mean</span>(df<span class="op">$</span>IQ, <span class="dt">na.rm =</span> T) <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">sd</span>(df<span class="op">$</span>IQ, <span class="dt">na.rm =</span> T))] &lt;-<span class="st"> </span><span class="ot">NA</span></code></pre></div>
<p> </p>
<p>Of course, fewer comands doesn’t necessarily mean better code. The above has the benefit of not creating any additional objects (<code>m_iq</code>, <code>condition_lo</code>, <em>etc.</em>) and not cluttering your environment. However, it may be less intelligible to a novice <code>R</code> user (the annotation does help though).</p>
<p>A particularly smart an elegant way would be to realise that the condition above is the same as saying we want all the points x<sub>i</sub> for which <span class="math inline">\(|x_i - Mean(x)| &gt; 2 \times 15.34\)</span>. The <span class="math inline">\(x_i - Mean(x)\)</span> has the effect of centring x so that its mean is zero and the absolute value (<span class="math inline">\(|...|\)</span>) disregards the sign. Thus <span class="math inline">\(|x| &gt; 1\)</span> is the same as <span class="math inline">\(x &lt; -1\)</span> <strong>OR</strong> <span class="math inline">\(x &gt; 1\)</span>.</p>
<p>Good, so the condition we want to apply to subset the <code>IQ</code> variable of <code>df</code> is <code>abs(df$IQ - mean(df$IQ, na.rm = T)) &gt; 2 * sd(df$IQ, na.rm = T)</code>. The rest, is the same:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df<span class="op">$</span>IQ[<span class="kw">abs</span>(df<span class="op">$</span>IQ <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(df<span class="op">$</span>IQ, <span class="dt">na.rm =</span> T)) <span class="op">&gt;</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">sd</span>(df<span class="op">$</span>IQ, <span class="dt">na.rm =</span> T)] &lt;-<span class="st"> </span><span class="ot">NA</span></code></pre></div>
<p> </p>
<p>This is quite a neat way of replacing outliers with <code>NA</code>s and code like this shows a desire to make things elegant and efficient. However, <strong>all three approaches discussed above</strong> (and potentially others) <strong>are correct</strong>. If it works, it’s fine!</p>
<p> </p>
<p><strong>Elementary, my dear Watson!</strong> ;)</p>
</div>
</div>
<div id="for-pudding" class="section level1">
<h1>For pudding…</h1>
<p>Following the principles detailed above is guaranteed to make you a better programmer so we hope you will stick to them. To help you along the way just that tiny bit more, here are a few additional tips based on our observations of your work in the labs.</p>
<div id="break-it-down" class="section level2">
<h2>Break it down</h2>
<p>Maybe you find yourself struggling with a task and turn to StackOverflow for help. Maybe you manage to find a ready-made answer to your problem or maybe some helpful soul writes one just for you. And maybe it works but you don’t quite understand why.</p>
<p>These things happen and sometimes a line of code can appear quite obscure. Take for example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10</span>) <span class="kw">eval</span>(<span class="kw">parse</span>(<span class="dt">text =</span> <span class="kw">paste0</span>(
  <span class="st">&quot;df_&quot;</span>, i, <span class="st">&quot; &lt;- as.data.frame(matrix(rnorm(100 * &quot;</span>, i ,<span class="st">&quot;, 0, &quot;</span>, i, <span class="st">&quot;), ncol = i))&quot;</span>)))</code></pre></div>
<p>When faced with a bit of code like this, it is generally a good idea to try to reverse-engineer it. Let’s give it a go.</p>
<p>First, we can see that this is a <code>for</code> loop that repeats itself 10 times: it starts by assigning the value of <code>1</code> to the iterator object <code>i</code>, then executes the code, increments <code>i</code> by 1 and repeats until <code>i == 10</code>. So to look what the code inside the loop does, we need to set <code>i</code> to some value (<code>1</code> is a reasonable choice).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">i &lt;-<span class="st"> </span><span class="dv">1</span></code></pre></div>
<p>Now, let’s start by running the code <em>from the innermost command outwards</em>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">paste0</span>(<span class="st">&quot;df_&quot;</span>, i, <span class="st">&quot; &lt;- as.data.frame(matrix(rnorm(100 * &quot;</span>, i ,<span class="st">&quot;, 0, &quot;</span>, i, <span class="st">&quot;), ncol = i))&quot;</span>)</code></pre></div>
<pre><code>## [1] &quot;df_1 &lt;- as.data.frame(matrix(rnorm(100 * 1, 0, 1), ncol = i))&quot;</code></pre>
<p>Right, so the first command created a character string that looks like a command. Let’s break it down even further:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rnorm</span>(<span class="dv">100</span> <span class="op">*</span><span class="st"> </span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>)</code></pre></div>
<pre><code>##   [1]  0.20954001  0.32389622 -0.37283508  0.06269738 -0.43944237
##   [6] -0.02971048  0.33167523  0.87613630  0.12066443  1.22960802
##  [11]  0.03880961 -0.36142638  1.69867485 -0.46379760  1.05567907
##  [16]  0.40706833  0.25091917  0.34659071 -0.56301006 -0.31952032
##  [21]  0.78593787  1.95669880  0.14824351  1.56030885 -0.98926565
##  [26] -0.80915244  0.08945734 -1.62738799 -1.05697179 -1.75220222
##  [31] -0.29391196 -0.13252925  0.13654792  0.24136139  0.08615494
##  [36]  1.11004042 -0.70139385 -0.35972937 -0.88680865 -1.63218801
##  [41] -0.41301727 -0.53387524  0.94790194  0.71916129 -0.16331570
##  [46]  1.34491080  1.44300060  0.33820727 -0.19126662  0.53843328
##  [51] -1.23718066 -0.02473555 -0.97911969  0.29637348 -0.66693251
##  [56]  0.29288841  0.18427546 -0.44233334 -0.28808903 -1.34834318
##  [61]  1.71051339 -2.18397948 -0.27129820 -1.58630719  0.39201312
##  [66] -0.71061021 -0.55363487 -0.90701430 -2.97942625  0.69433419
##  [71] -0.55669372  0.42582168 -0.03448993 -1.12345523 -0.81422757
##  [76]  0.21169668 -0.86538853  0.42856097  1.59318164  1.37067953
##  [81] -0.90282830  0.25127218  1.18658370 -0.49531115 -0.05869356
##  [86] -1.01300326 -1.60729983  0.85693928 -1.07644969  1.45898747
##  [91] -0.04104904  0.55746811  0.10122818  0.54807689 -0.25196015
##  [96]  1.65730231  0.80990206 -0.67484874 -1.80270986 -1.93369359</code></pre>
<p>OK, this is easy. The first bit generates <span class="math inline">\(100 \times i\)</span> random numbers with a mean of zero and a standard deviation of <em>i</em>. Let’s move one layer out:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># printout truncated to first 10 lines</span>
<span class="kw">matrix</span>(<span class="kw">rnorm</span>(<span class="dv">100</span> <span class="op">*</span><span class="st"> </span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>), <span class="dt">ncol =</span> i)</code></pre></div>
<pre><code>##                [,1]
##   [1,]  0.592449112
##   [2,]  0.408159854
##   [3,] -2.272998915
##   [4,]  0.427715149
##   [5,] -0.720533341
##   [6,]  1.273581166
##   [7,] -1.332828102
##   [8,]  0.550537343
##   [9,] -0.451407689
##  [10,] -1.078032764
##  [ reached getOption(&quot;max.print&quot;) -- omitted 90 rows ]</code></pre>
<p>This command put those numbers into a <code>matrix</code> with 100 rows and <em>i</em> columns. Next:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">matrix</span>(<span class="kw">rnorm</span>(<span class="dv">100</span> <span class="op">*</span><span class="st"> </span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>), <span class="dt">ncol =</span> i))</code></pre></div>
<p>This line converts the matrix into a <code>data.frame</code> and stored it in an object called “<code>df_i</code>”. Remember, <code>i</code> takes values of 1-10, increasingly each time the loop is repeated.</p>
<p>All good thus far but why is the command a character string (in “quotes”)? What is that good for? Well, turns out that the <code>parse()</code> function can take a string with a valid <code>R</code> code inside and turn it to an <code>expression</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">parse</span>(<span class="dt">text =</span> <span class="kw">paste0</span>(<span class="st">&quot;df_&quot;</span>, i, <span class="st">&quot; &lt;- as.data.frame(matrix(rnorm(100 * &quot;</span>,
                    i ,<span class="st">&quot;, 0, &quot;</span>, i, <span class="st">&quot;), ncol = i))&quot;</span>))</code></pre></div>
<pre><code>## expression(df_1 &lt;- as.data.frame(matrix(rnorm(100 * 1, 0, 1), 
##     ncol = i)))</code></pre>
<p> </p>
<p>This expression can be then evaluated using the <code>eval()</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">eval</span>(<span class="kw">parse</span>(<span class="dt">text =</span> <span class="kw">paste0</span>(
  <span class="st">&quot;df_&quot;</span>, i, <span class="st">&quot; &lt;- as.data.frame(matrix(rnorm(100 * &quot;</span>, i , <span class="st">&quot;, 0, &quot;</span>, i, <span class="st">&quot;), ncol = i))&quot;</span>)))

<span class="co"># printout truncated</span>
df_<span class="dv">1</span></code></pre></div>
<pre><code>##               V1
## 1   -0.093052543
## 2   -1.000687541
## 3    1.218611659
## 4   -0.094683601
## 5    0.758951880
## 6   -0.383428923
## 7    1.122102965
## 8   -0.404385411
## 9    1.567832259
## 10  -0.156694971
##  [ reached getOption(&quot;max.print&quot;) -- omitted 90 rows ]</code></pre>
<p>So what the entire loop does is create 10 data frames named <code>df_1</code> to <code>df_10</code>, each containing 100 rows and a different number of columns (1 for <code>df_1</code>, 6 for <code>df_6</code> <em>etc.</em>) with random numbers. Moreover, each <code>data.frame</code> contains random numbers with different standard deviations.</p>
<p>And so, just like that, with a single line of code we can create 10 (or more!) different <code>R</code> objects with different properties. Cool, isn’t it? Hope this example demonstrates how, using systematic reverse-engineering, you can come to understand even a daunting-looking code with functions you haven’t seen before.</p>
<p> </p>
</div>
<div id="handy-functions-that-return-logicals" class="section level2">
<h2>Handy functions that return logicals</h2>
<p>Finally, here are some useful functions with which you might want to familiarise yourself. They will make cleaning your data much easier.</p>
<ul>
<li><p><code>==</code>, takes a <code>vector</code>, <code>matrix</code>, or a <code>data.frame</code> and compares every element thereof to <strong>a single</strong> value. Returns a <code>logical vector</code> with <code>TRUE</code> for elements that are <em>equal to</em> the compared value and <code>FALSE</code> otherwise. Comparing <code>NA</code> returns <code>NA</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>, <span class="ot">NA</span>) <span class="op">==</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">100</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">8</span>, <span class="dv">5</span>, <span class="dv">9</span>)</code></pre></div>
<pre><code>## [1] FALSE  TRUE FALSE FALSE  TRUE    NA</code></pre></li>
<li><code>&lt;</code>, same as <code>==</code>, but <code>TRUE</code> is returned if element is <em>less than</em> the compared value.</li>
<li><code>&gt;</code>, same as <code>==</code>, but <code>TRUE</code> is returned if element is <em>greater than</em> the compared value.</li>
<li><code>&lt;=</code>, same as <code>==</code>, but <code>TRUE</code> is returned if element is <em>less than or equal to</em> the compared value. In other words, it is a negation of (complementary operation to) <code>&gt;</code>.</li>
<li><code>&gt;=</code>, same as <code>==</code>, but <code>TRUE</code> is returned if element is <em>greater than or equal to</em> the compared value. Negation of <code>&lt;</code>.</li>
<li><p><code>%in%</code>, same as <code>==</code>, but can take a <code>vector</code> on the right hand side. Each element of the <code>vector</code>/<code>matrix</code>/<code>data.frame</code> to the left is compared to each element of the vector to the right. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>, <span class="ot">NA</span>) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">100</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">8</span>)</code></pre></div>
<pre><code>## [1] FALSE  TRUE FALSE  TRUE FALSE FALSE</code></pre></li>
<li>all functions that begin with ‘<code>is</code>’, <em>e.g.</em>:
<ul>
<li><code>is.na()</code>, takes a <code>vector</code>, <code>matrix</code>, or a <code>data.frame</code> and returns a <code>logical vector</code> with <code>TRUE</code> if given element is an <code>NA</code> and <code>FALSE</code> otherwise.</li>
<li><code>is.numeric()</code>, takes any object and returns <code>TRUE</code> if it is a numeric vector and <code>FALSE</code> otherwise.</li>
<li><code>is.factor()</code>, <code>is.matrix()</code>, <code>is.data.frame()</code>, <code>is.list()</code>, same as <code>is.numeric()</code> but return <code>TRUE</code> if the object provided is a <code>factor</code>, <code>matrix</code>, <code>data.frame</code>, or <code>list</code>, respectively.</li>
<li><code>isTRUE()</code>, returns <em>a single</em> <code>TRUE</code> if the expression provided evaluates to <code>TRUE</code> and <em>a single</em> <code>FALSE</code> otherwise. Only <code>isTRUE(TRUE)</code> returns <code>TRUE</code>. <code>isTRUE(FALSE)</code>, <code>isTRUE(c(TRUE, TRUE))</code> and anything else returns <code>FALSE</code>. Works with <code>NA</code>s so can be useful for combining with logical operators that return <code>NA</code> when comparing missing values. For example</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="ot">NA</span> <span class="op">&gt;</span><span class="st"> </span><span class="dv">4</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">isTRUE</span>(<span class="ot">NA</span> <span class="op">&gt;</span><span class="st"> </span><span class="dv">4</span>)</code></pre></div>
<pre><code>## [1] FALSE</code></pre></li>
<li><code>any()</code>, takes a logical vector and returns <code>TRUE</code> if <strong>any</strong> of its elements equals <code>TRUE</code>, and <code>FALSE</code> otherwise, <em>e.g.,</em> <code>any(1:5</code> <code>&gt; 4)</code> returns <code>TRUE</code>.</li>
<li><code>all()</code>, like <code>any()</code> but returns <code>TRUE</code> only if <strong>all</strong> of the elements of the vector provided are <code>TRUE</code>.</li>
<li><p><code>all.equal()</code>, takes two objects and returns <code>TRUE</code> if they are identical and a <em>vector of all discrepancies</em> otherwise. Sensitive to attributes so <code>all.equal(1:5, factor(1:5))</code> does not return <code>TRUE</code>. Good to use along with <code>isTRUE()</code>!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">all.equal</span>(df, df)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">all.equal</span>(df, my_list)</code></pre></div>
<pre><code>##  [1] &quot;Names: 3 string mismatches&quot;                                       
##  [2] &quot;Attributes: &lt; names for target but not for current &gt;&quot;             
##  [3] &quot;Attributes: &lt; Length mismatch: comparison on first 0 components &gt;&quot;
##  [4] &quot;Length mismatch: comparison on first 3 components&quot;                
##  [5] &quot;Component 1: Lengths: 325, 20&quot;                                    
##  [6] &quot;Component 1: Attributes: &lt; target is NULL, current is list &gt;&quot;     
##  [7] &quot;Component 1: target is numeric, current is matrix&quot;                
##  [8] &quot;Component 2: Modes: numeric, character&quot;                           
##  [9] &quot;Component 2: Lengths: 325, 5&quot;                                     
## [10] &quot;Component 2: target is numeric, current is character&quot;             
##  [ reached getOption(&quot;max.print&quot;) -- omitted 5 entries ]</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># use with isTRUE() if T/F desired</span>
<span class="kw">isTRUE</span>(<span class="kw">all.equal</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>, <span class="kw">factor</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>)))</code></pre></div>
<pre><code>## [1] FALSE</code></pre></li>
<li><p><code>&amp;</code>, “AND” takes two Booleans and returns <code>TRUE</code> if <strong>both of them</strong> are <code>TRUE</code>, <code>NA</code> if either is <code>NA</code>, and <code>FALSE</code> otherwise. Can be applied over two <code>logical vectors</code> of the <em>same length</em>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">c</span>(T, T, F) <span class="op">&amp;</span><span class="st"> </span><span class="kw">c</span>(T, T, T)</code></pre></div>
<pre><code>## [1]  TRUE  TRUE FALSE</code></pre></li>
<li><code>|</code>, “OR” is the same as <code>&amp;</code> but returns <code>TRUE</code> if <strong>either or both</strong> of the two compared elements is <code>TRUE</code>.</li>
<li><p><code>xor()</code>, “exclusive OR” is same as above but returns <code>TRUE</code> only if <strong>either</strong> the first or the second, <strong>but not both</strong> of the two compared elements, is <code>TRUE</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">xor</span>(<span class="kw">c</span>(T, F, F), <span class="kw">c</span>(T, F, T))</code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE</code></pre></li>
<li><p><code>&amp;&amp;</code> and <code>||</code>, single-element versions of <code>&amp;</code> and <code>|</code>. They only compare the first element of both of the vectors provided (<em>i.e.,</em> x[1] vs y[1]):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">c</span>(T, F, F) <span class="op">||</span><span class="st"> </span><span class="kw">c</span>(T, F, T)</code></pre></div>
<pre><code>## [1] TRUE</code></pre></li>
<li>all of the above can be negated using the ‘<code>!</code>’ operator, <em>e.g.</em>:
<ul>
<li><code>x != y</code></li>
<li><code>!x &gt; y</code></li>
<li><code>!is.na(x)</code></li>
<li><code>!any(is.na(x))</code> is equivalent to <code>all(!is.na(x))</code></li>
<li><code>!(x &amp; y)</code> is equivalent to <code>xor(x, y) | (!x &amp; !y)</code></li>
</ul></li>
</ul>
<p> </p>
<p> </p>
<p>So that’s it for now. We will keep an eye out and if we notice things some of you seem to struggle with, we’ll expand this file. Feel free to let us know if you have any suggestions on what to include in future versions. Until then, happy coding!</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Open Science Collaboration. (2015). Estimating the reproducibility of psychological science. <em>Science, 349</em>(6251), aac4716.<a href="#fnref1">↩</a></p></li>
<li id="fn2"><p>An important insight immortalised by Newton Crosby in the 1986 cult movie <a href="http://www.imdb.com/title/tt0091949/?ref_=ttqt_qt_tt" target="_blank">Short Circuit</a>: “It’s a machine, Schroeder. It doesn’t get pissed off. It doesn’t get happy, it doesn’t get sad, it doesn’t laugh at your jokes. <em>It just runs programs.</em>”<a href="#fnref2">↩</a></p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
